//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conferance_Hall_Book.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int bookingno { get; set; }
        public string companyname { get; set; }
        public string bookingdate { get; set; }
        public string bookingtime { get; set; }
        public Nullable<int> mambercount { get; set; }
        public string systems { get; set; }
        public string internet { get; set; }
        public string telephone { get; set; }
    }
}
